=== Michal18R/Wydzialy/Dane_Wydzialy.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="Wydzialy">
  
  <xs:complexType>
    <xs:sequence>
     <xs:element ref="Wydzial" minOccurs="1" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>
  </xs:element>
  
  <xs:element name="Wydzial">
  
  <xs:complexType>
    <xs:sequence>
     <xs:element name="Nazwa" minOccurs="1" maxOccurs="1" type="xs:string" />
     <xs:element name="Adres" minOccurs="1" maxOccurs="unbounded" />
     <xs:element ref="Pracownicy" />
     <xs:element ref="Przedmioty" />
     </xs:sequence>	
    <xs:attribute name="id" use="required" type="xs:ID"/>	 
  </xs:complexType>
      
  </xs:element>
  
  <xs:element name="Pracownicy">
  
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="Pracownik" minOccurs="1" maxOccurs="unbounded" />
    </xs:sequence>
    <xs:attribute name="id" use="required" type="xs:ID"/>
  </xs:complexType>
  </xs:element>
  
  <xs:element name="Pracownik">
  
  <xs:complexType>
    <xs:sequence>
      <xs:element name="Imie" type="xs:string" minOccurs="1" maxOccurs="1" />
      <xs:element name="Nazwisko" type="xs:string" minOccurs="1" maxOccurs="1" />
      <xs:element name="Tytul" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
      <xs:element name="Kategoria" minOccurs="0" maxOccurs="3">
		
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Naukowy"/>
            <xs:enumeration value="Administracyjny"/>
            <xs:enumeration value="Techniczny"/>
          </xs:restriction>
        </xs:simpleType>
		  
      </xs:element>
      <xs:element ref="Adres-Pracownika" minOccurs="1" maxOccurs="unbounded" />
    </xs:sequence>
      <xs:attribute name="id" use="required" type="xs:ID"/>
        <xs:attribute name="idref" type="xs:IDREF" />
    </xs:complexType>
	
  </xs:element>
  
  <xs:element name="Adres-Pracownika">
  
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Ulica" type="xs:string" />
        <xs:element name="Numer-Ulicy" type="xs:integer" />
        <xs:element name="Kod-Pocztowy">
		
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:minLength value="6"/>
              <xs:maxLength value="6"/>
              <xs:pattern value="\d{2}-\d{3}"/>
            </xs:restriction>
          </xs:simpleType>
		  
        </xs:element>
        <xs:element name="Miejscowosc" type="xs:string" />
      </xs:sequence>
    </xs:complexType>
	
  </xs:element>
  
  <xs:element name="Przedmioty">
  
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Przedmiot" minOccurs="1" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>	
  </xs:element>
  
  <xs:element name="Przedmiot">
  
  <xs:complexType>
    <xs:all>
      <xs:element name="Nazwa" type="xs:string" />
      <xs:element name="Opis" type="xs:string" />
      <xs:element name="Zbior-Prowadzacych">
		
        <xs:complexType>
          <xs:sequence>
            <xs:element ref="Prowadzacy" minOccurs="1" maxOccurs="unbounded" />
          </xs:sequence>
        </xs:complexType>
		  
      </xs:element>
		
      <xs:element name="Studenci">
        <xs:complexType>
          <xs:sequence>
            <xs:element ref="Student" minOccurs="6" maxOccurs="400" />
          </xs:sequence>
        </xs:complexType>
		  
      </xs:element>
		
    </xs:all>
	  
    <xs:attribute name="id" use="required" type="xs:ID"/>
    </xs:complexType>
	
  </xs:element>
  
  <xs:element name="Student">
  
  <xs:complexType>
    <xs:all>
      <xs:element name="Imie-Studenta" type="xs:string" />
      <xs:element name="Nazwisko-Studenta" type="xs:string" />
      <xs:element name="Numer-Indeksu-Studenta" type="xs:integer" /> 	  
    </xs:all>
    <xs:attribute name="id" use="required" type="xs:ID"/>
  </xs:complexType>
	
  </xs:element>
  
  <xs:element name="Prowadzacy">
  
  <xs:complexType>
      <xs:attribute name="idref" use="required" type="xs:IDREF" />
  </xs:complexType>
	
  </xs:element>
  
</xs:schema>

=== Michal18R/Wydzialy/Dane_Wydzialy.xml
<?xml version="1.0" encoding="UTF-8"?>
<Wydzialy xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Dane_Wydzialy.xsd">

  <Wydzial id="WYDZIAL_NR1">
    <Nazwa>Wydział Historii</Nazwa>
    <Adres>Uniwersytetu Poznańskiego 7</Adres>
    <Adres>Kowalewskiego 3</Adres>
	<Adres>Świetego Macieja 12</Adres>
	<Adres>Koło Spodku 121</Adres>
	
    <Pracownicy id="PRACOWNICY_NR1">
	
      <Pracownik id="PRACOWNIK_NR1">
        <Imie>Krzysztof</Imie>
        <Nazwisko>Rodak</Nazwisko>
        <Tytul>Doktor Habilitowany</Tytul>
        <Kategoria>Naukowy</Kategoria>
        <Adres-Pracownika>
          <Ulica>Kolumba</Ulica>
          <Numer-Ulicy>9</Numer-Ulicy>
          <Kod-Pocztowy>61-444</Kod-Pocztowy>
          <Miejscowosc>Poznań</Miejscowosc>
        </Adres-Pracownika>
      </Pracownik>
	  
      <Pracownik id="PRACOWNIK_NR2">
        <Imie>Daniela</Imie>
        <Nazwisko>Kubo</Nazwisko>
        <Tytul>Inżynier</Tytul>
        <Kategoria>Administracyjny</Kategoria>
        <Adres-Pracownika>
          <Ulica>Mickiewicza</Ulica>
          <Numer-Ulicy>34</Numer-Ulicy>
          <Kod-Pocztowy>61-440</Kod-Pocztowy>
          <Miejscowosc>Poznań</Miejscowosc>
        </Adres-Pracownika>
      </Pracownik>
	  
	  <Pracownik id="PRACOWNIK_NR3">
        <Imie>Karol</Imie>
        <Nazwisko>Potrzebny</Nazwisko>
        <Kategoria>Techniczny</Kategoria>
        <Adres-Pracownika>
          <Ulica>Peca</Ulica>
          <Numer-Ulicy>4</Numer-Ulicy>
          <Kod-Pocztowy>61-439</Kod-Pocztowy>
          <Miejscowosc>Poznań</Miejscowosc>
        </Adres-Pracownika>
      </Pracownik>
    
	
	<Pracownik id="PRACOWNIK_NR4">
        <Imie>Robert</Imie>
        <Nazwisko>Zimny</Nazwisko>
        <Tytul>Doktor</Tytul>
        <Kategoria>Naukowy</Kategoria>
        <Adres-Pracownika>
          <Ulica>Dąbrowskiego</Ulica>
          <Numer-Ulicy>90</Numer-Ulicy>
          <Kod-Pocztowy>61-428</Kod-Pocztowy>
          <Miejscowosc>Poznań</Miejscowosc>
        </Adres-Pracownika>
      </Pracownik>
	
	</Pracownicy>
    <Przedmioty>
      <Przedmiot id="PRZEDMIOT_NR1">
        <Nazwa>Historia Sztuki</Nazwa>
        <Opis>Historia Sztuki od Średniowiecza po Renesans</Opis>
		
        <Zbior-Prowadzacych>
          <Prowadzacy idref="PRACOWNIK_NR1" />
        </Zbior-Prowadzacych>
		
        <Studenci>
          <Student id="STUDENT_NR1">
            <Imie-Studenta>Adam</Imie-Studenta>
            <Nazwisko-Studenta>Pec</Nazwisko-Studenta>
			<Numer-Indeksu-Studenta>439477</Numer-Indeksu-Studenta>
          </Student>
		  
		  <Student id="STUDENT_NR2">
            <Imie-Studenta>Karol</Imie-Studenta>
            <Nazwisko-Studenta>Lolek</Nazwisko-Studenta>
			<Numer-Indeksu-Studenta>439478</Numer-Indeksu-Studenta>
          </Student>
		  
		  <Student id="STUDENT_NR3">
            <Imie-Studenta>Karolina</Imie-Studenta>
            <Nazwisko-Studenta>Man</Nazwisko-Studenta>
			<Numer-Indeksu-Studenta>439479</Numer-Indeksu-Studenta>
          </Student>
		  
		  <Student id="STUDENT_NR4">
            <Imie-Studenta>Ula</Imie-Studenta>
            <Nazwisko-Studenta>Manien</Nazwisko-Studenta>
			<Numer-Indeksu-Studenta>439480</Numer-Indeksu-Studenta>
          </Student>
		  
		  <Student id="STUDENT_NR5">
            <Imie-Studenta>Tomek</Imie-Studenta>
            <Nazwisko-Studenta>Kwal</Nazwisko-Studenta>
			<Numer-Indeksu-Studenta>439481</Numer-Indeksu-Studenta>
          </Student>
		  
		  <Student id="STUDENT_NR6">
            <Imie-Studenta>Michał</Imie-Studenta>
            <Nazwisko-Studenta>Kwalowski</Nazwisko-Studenta>
			<Numer-Indeksu-Studenta>439482</Numer-Indeksu-Studenta>
          </Student>
		  
		  <Student id="STUDENT_NR7">
            <Imie-Studenta>Michał</Imie-Studenta>
            <Nazwisko-Studenta>Pena</Nazwisko-Studenta>
			<Numer-Indeksu-Studenta>439483</Numer-Indeksu-Studenta>
          </Student>
		  
		  <Student id="STUDENT_NR8">
            <Imie-Studenta>Robert</Imie-Studenta>
            <Nazwisko-Studenta>Tomyl</Nazwisko-Studenta>
			<Numer-Indeksu-Studenta>439484</Numer-Indeksu-Studenta>
          </Student>
		  
		  <Student id="STUDENT_NR9">
            <Imie-Studenta>Ziemowit</Imie-Studenta>
            <Nazwisko-Studenta>Koko</Nazwisko-Studenta>
			<Numer-Indeksu-Studenta>439485</Numer-Indeksu-Studenta>
          </Student>
		  
		  <Student id="STUDENT_NR10">
            <Imie-Studenta>Zuzia</Imie-Studenta>
            <Nazwisko-Studenta>Kokel</Nazwisko-Studenta>
			<Numer-Indeksu-Studenta>439486</Numer-Indeksu-Studenta>
          </Student>        
        </Studenci>
		
      </Przedmiot>
	  
	  <Przedmiot id="PRZEDMIOT_NR2">
        <Nazwa>Historia Matematyki</Nazwa>
        <Opis>Nauka Podstaw Matematyki w różnych kulturach</Opis>
		
        <Zbior-Prowadzacych>
          <Prowadzacy idref="PRACOWNIK_NR4" />
        </Zbior-Prowadzacych>
		
        <Studenci>
          <Student id="STUDENT_NR11">
            <Imie-Studenta>Adama</Imie-Studenta>
            <Nazwisko-Studenta>Peca</Nazwisko-Studenta>
			<Numer-Indeksu-Studenta>439487</Numer-Indeksu-Studenta>
          </Student>
		  
		  <Student id="STUDENT_NR12">
            <Imie-Studenta>Karola</Imie-Studenta>
            <Nazwisko-Studenta>Loleka</Nazwisko-Studenta>
			<Numer-Indeksu-Studenta>439488</Numer-Indeksu-Studenta>
          </Student>
		  
		  <Student id="STUDENT_NR13">
            <Imie-Studenta>Karol</Imie-Studenta>
            <Nazwisko-Studenta>Mana</Nazwisko-Studenta>
			<Numer-Indeksu-Studenta>439489</Numer-Indeksu-Studenta>
          </Student>
		  
		  <Student id="STUDENT_NR14">
            <Imie-Studenta>Ulek</Imie-Studenta>
            <Nazwisko-Studenta>Manienka</Nazwisko-Studenta>
			<Numer-Indeksu-Studenta>439490</Numer-Indeksu-Studenta>
          </Student>
		  
		  <Student id="STUDENT_NR15">
            <Imie-Studenta>Tomek</Imie-Studenta>
            <Nazwisko-Studenta>Kwalinski</Nazwisko-Studenta>
			<Numer-Indeksu-Studenta>439491</Numer-Indeksu-Studenta>
          </Student>
		  
		  <Student id="STUDENT_NR16">
            <Imie-Studenta>Michalina</Imie-Studenta>
            <Nazwisko-Studenta>Kwalowska</Nazwisko-Studenta>
			<Numer-Indeksu-Studenta>439492</Numer-Indeksu-Studenta>
          </Student>
		  
		  <Student id="STUDENT_NR17">
            <Imie-Studenta>Michał</Imie-Studenta>
            <Nazwisko-Studenta>Kowal</Nazwisko-Studenta>
			<Numer-Indeksu-Studenta>439493</Numer-Indeksu-Studenta>
          </Student>
		  
		 </Studenci>
      </Przedmiot>
	  
    </Przedmioty>
  </Wydzial>
  
  <Wydzial id="WYDZIAL_NR2">
    <Nazwa>Wydział Matematyki Stosowanej</Nazwa>
    <Adres>Uniwersytetu Polańskiego 17</Adres>
   
    <Pracownicy id="PRACOWNICY_NR2">
	
      <Pracownik id="PRACOWNIK_NR5">
        <Imie>Adam</Imie>
        <Nazwisko>Rodak</Nazwisko>
        <Tytul>Doktor Habilitowany</Tytul>
        <Kategoria>Naukowy</Kategoria>
        <Adres-Pracownika>
          <Ulica>Kolumbijskiego</Ulica>
          <Numer-Ulicy>18</Numer-Ulicy>
          <Kod-Pocztowy>61-333</Kod-Pocztowy>
          <Miejscowosc>Poznań</Miejscowosc>
        </Adres-Pracownika>
      </Pracownik>
	  
      <Pracownik id="PRACOWNIK_NR6">
        <Imie>Daniel</Imie>
        <Nazwisko>Kuborek</Nazwisko>
        <Tytul>Inżynier</Tytul>
        <Kategoria>Administracyjny</Kategoria>
        <Adres-Pracownika>
          <Ulica>Pecas</Ulica>
          <Numer-Ulicy>134</Numer-Ulicy>
          <Kod-Pocztowy>61-334</Kod-Pocztowy>
          <Miejscowosc>Poznań</Miejscowosc>
        </Adres-Pracownika>
      </Pracownik>
	  
	  <Pracownik id="PRACOWNIK_NR7">
        <Imie>Karolina</Imie>
        <Nazwisko>Potrzebna</Nazwisko>
        <Kategoria>Techniczny</Kategoria>
        <Adres-Pracownika>
          <Ulica>Kolanka</Ulica>
          <Numer-Ulicy>224</Numer-Ulicy>
          <Kod-Pocztowy>61-335</Kod-Pocztowy>
          <Miejscowosc>Poznań</Miejscowosc>
        </Adres-Pracownika>
      </Pracownik>
    
	
	<Pracownik id="PRACOWNIK_NR8">
        <Imie>Roberta</Imie>
        <Nazwisko>Zimna</Nazwisko>
        <Tytul>Doktor</Tytul>
        <Kategoria>Naukowy</Kategoria>
        <Adres-Pracownika>
          <Ulica>Dąbrowskiego</Ulica>
          <Numer-Ulicy>190</Numer-Ulicy>
          <Kod-Pocztowy>61-336</Kod-Pocztowy>
          <Miejscowosc>Poznań</Miejscowosc>
        </Adres-Pracownika>
      </Pracownik>
	  
	  <Pracownik id="PRACOWNIK_NR9">
        <Imie>Wacław</Imie>
        <Nazwisko>Pierwszy</Nazwisko>
        <Tytul>Doktor Habilitowany</Tytul>
        <Kategoria>Naukowy</Kategoria>
        <Adres-Pracownika>
          <Ulica>Dąbrowskiego</Ulica>
          <Numer-Ulicy>200</Numer-Ulicy>
          <Kod-Pocztowy>61-337</Kod-Pocztowy>
          <Miejscowosc>Poznań</Miejscowosc>
        </Adres-Pracownika>
      </Pracownik>
	</Pracownicy>
	
    <Przedmioty>
      <Przedmiot id="PRZEDMIOT_NR3">
        <Nazwa>Podstawy Matematyki</Nazwa>
        <Opis>Nauka podstaw Matematyki</Opis>
		
        <Zbior-Prowadzacych>
          <Prowadzacy idref="PRACOWNIK_NR1" />
		  <Prowadzacy idref="PRACOWNIK_NR5" />
        </Zbior-Prowadzacych>
		
        <Studenci>
          <Student id="STUDENT_NR18">
            <Imie-Studenta>Adamiek</Imie-Studenta>
            <Nazwisko-Studenta>Pecel</Nazwisko-Studenta>
			<Numer-Indeksu-Studenta>439500</Numer-Indeksu-Studenta>
          </Student>
		  
		  <Student id="STUDENT_NR19">
            <Imie-Studenta>Karolek</Imie-Studenta>
            <Nazwisko-Studenta>Kok</Nazwisko-Studenta>
			<Numer-Indeksu-Studenta>439501</Numer-Indeksu-Studenta>
          </Student>
		  
		  <Student id="STUDENT_NR20">
            <Imie-Studenta>Mania</Imie-Studenta>
